### ISSUE TITLE
Issue: KeyError: 'data'

### ISSUE THREAD

**Issue by theandrepo** [huggingface/diarizers#14]
Hi.

I tried to do some training using a synthetic dataset but it ends with KeyError: 'data'

The command  is :

`python train_segmentation.py --dataset_name=Obiactum/synthetic-speaker-diarization-dataset-ita --split_on_subset=data --model_name_or_path=pyannote/segmentation-3.0 --output_dir=./speaker-segmentation-fine-tuned-ita --do_train --do_eval --learning_rate=1e-3 --num_train_epochs=5 --lr_scheduler_type=cosine --per_device_train_batch_size=32 --per_device_eval_batch_size=32 --evaluation_strategy=epoch --save_strategy=epoch --preprocessing_num_workers=2 --dataloader_num_workers=2 --logging_steps=100 --load_best_model_at_end --push_to_hub`

It seems to work and start but after a while I get an error. Any clue ?

Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 429M/429M [01:16<00:00, 5.62MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 428M/428M [01:34<00:00, 4.55MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 420M/420M [01:18<00:00, 5.35MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 427M/427M [01:28<00:00, 4.83MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 434M/434M [01:12<00:00, 5.96MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 428M/428M [01:42<00:00, 4.17MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 428M/428M [00:44<00:00, 9.70MB/s]
Generating train split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1600/1600 [01:18<00:00, 20.32 examples/s]
Traceback (most recent call last):
  File "D:\02-GENAI\diarizers\train_segmentation.py", line 89, in <module>
    train_testvalid = dataset[str(data_args.split_on_subset)].train_test_split(test_size=0.2, seed=0)
                      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\02-GENAI\diarizers\venv\Lib\site-packages\datasets\dataset_dict.py", line 75, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'data'


I am using 
CUDA 12.1
Python 3.11.6
and a virtual env with all the requirements installed.

**Comment by theandrepo** [comment]
Unfortunately I haven't look well and it was just a matter of the parameters I was using.
split_on_subset=data was removed.
