### ISSUE TITLE
Preprocessing consumes all available memory

### ISSUE THREAD

**Issue by Jamiroquai88** [huggingface/diarizers#6]
Hello, I wanted to try diarizers repo to fine-tune the model on my data. 
I slightly rewrote the training script to load my own data, e.g.
```python
dataset = SpeakerDiarizationDataset(
        {
            'train': train_audio_files,
            'validation': dev_audio_files
        },
        {
            'train': train_rttm_files,
            'validation': dev_rttm_files
        }).construct_dataset()
``` 
I am able to train on a smaller set, but once I use more data, preprocessing consumes all available (1T+) memory. It is only at 4% progress at that point. Any pointers on where to look, so I can fix this? I must say that I use a lot of data, in this case probably more than 60.000 hours.

I trained pyannote3 segmentation models before, but with my own scripts and I never had this issue.

**Comment by Jamiroquai88** [comment]
So I need to confirm that even when using my dev set (550 hours) to train I see very similar behaviour. In this case, it finished successfully, but memory ramped up to 100% available, probably more than 1.2T. I would expect this to work.

**Comment by kamilakesbi** [comment]
Hi @Jamiroquai88, 

Thank you for submitting this issue! 

Would you agree to share with us your data (at least your dev set) so that we try to reproduce this behavior ? it will be hard for us to debug if we can't reproduce it.  

Here are a few pointers to look at: 

- How long are the audios you are trying to load? each audio sample is loaded into memory on the fly, which could cause memory issues if the audios are very long. 

- Preprocessing is done on-the-fly during training in pyannote, whereas here we preprocess the entire dataset with `Preprocess` before feeding it to the trainer. It might also explain the problem you are facing. 

- Are you using a batched `.map` function to perform preprocessing ? if so, you can tweak the batch size and play with the dataset `.map` parameters to reduce RAM (you can refer to this [comment](https://github.com/huggingface/audio-transformers-course/issues/57#issuecomment-1604516814))

Please let us know if you any of these pointers helped you solve this issue!

**Comment by Jamiroquai88** [comment]
Hi @kamilakesbi, so I decided to try IterableDataset, but I am having issues.
I tried to write an iterator that yields a single audio with timestamps, etc:
```python
def iterable_dataset_generator(annotations_paths, audio_paths, diarization_dataset_object):
    for annotation, audio in zip(annotations_paths, audio_paths):
        if diarization_dataset_object.annotations_type == "rttm":
            timestamps_start_file, timestamps_end_file, speakers_file = (
                diarization_dataset_object.process_rttm_file(annotation))
        elif diarization_dataset_object.annotations_type == "cha":
            timestamps_start_file, timestamps_end_file, speakers_file = (
                diarization_dataset_object.process_cha_file(annotation))
        else:
            raise ValueError("Unsupported annotations type")

        yield {
            "audio": audio,
            "timestamps_start": timestamps_start_file,
            "timestamps_end": timestamps_end_file,
            "speakers": speakers_file,
        }
```
Initializing like this
```python
def construct_dataset(self, num_proc=1):
    """Main method to construct the dataset

    Returns:
        self.spd_dataset: HF dataset compatible with diarizers.
    """
    for subset in self.audio_paths:
        self.spd_dataset[subset] = IterableDataset.from_generator(
            iterable_dataset_generator,
            gen_kwargs={
                'annotations_paths': self.annotations_paths[subset],
                'audio_paths': self.audio_paths[subset],
                'diarization_dataset_object': self
            }
        )
```
In all the examples that I see people do 
```python
self.spd_dataset[subset] = self.spd_dataset.cast_column("audio", Audio(sampling_rate=self.sample_rate))
```
but this gives me an error
```
Traceback (most recent call last):
  File "/shared/jprofant/Github/diarizers/train_segmentation_rev.py", line 89, in <module>
    }).construct_dataset()
  File "/shared/jprofant/Github/diarizers/src/diarizers/data/speaker_diarization.py", line 200, in construct_dataset
    self.spd_dataset[subset] = self.spd_dataset.cast_column("audio", Audio(sampling_rate=self.sample_rate))
  File "/home/ubuntu/miniconda3/envs/diarizers/lib/python3.10/site-packages/datasets/dataset_dict.py", line 2255, in cast_column
    {k: dataset.cast_column(column=column, feature=feature) for k, dataset in self.items()}
  File "/home/ubuntu/miniconda3/envs/diarizers/lib/python3.10/site-packages/datasets/dataset_dict.py", line 2255, in <dictcomp>
    {k: dataset.cast_column(column=column, feature=feature) for k, dataset in self.items()}
  File "/home/ubuntu/miniconda3/envs/diarizers/lib/python3.10/site-packages/datasets/iterable_dataset.py", line 2131, in cast_column
    info.features[column] = feature
TypeError: 'NoneType' object does not support item assignment
```
So I guess that `audio` is not loaded yet.
When I don't do `.cast_column()` I go further in the code, but again, not sure what to do about audio (since it probably isn't loaded):
```
File "/shared/jprofant/Github/diarizers/train_segmentation_rev.py", line 131, in <lambda>
    lambda file: preprocessor(file, random=False, overlap=0.0),
  File "/shared/jprofant/Github/diarizers/src/diarizers/data/preprocess.py", line 204, in __call__
    start_positions = self.get_start_positions(file, overlap)
  File "/shared/jprofant/Github/diarizers/src/diarizers/data/preprocess.py", line 173, in get_start_positions
    sample_rate = file["audio"][0]["sampling_rate"]
TypeError: string indices must be integers
```

Any idea what I am doing wrong? I guess I should somehow load audio inside the generator, but not sure how.
Even in this example they use `.cast_column()` https://huggingface.co/docs/datasets/audio_load

**Comment by kamilakesbi** [comment]
Hi @Jamiroquai88, 

Could you share with me a min reproducer of the error you get ? I can try to reproduce using the Callhome dataset. 

- Regarding the issue with `audio`: Are you sure that you're passing the right audio paths ? can you correctly load the audios when not using an iterable dataset ? you could also try loading directly the audios in `iterable_dataset_generator ` and  return them in this format: 

```
audio = {
     'array': audio np array, 
     'sample_rate': sampling rate (int) 
} 
```

This would be to make sure that you can load them correctly before using `.cast_column()`. 

- Regarding the memory issue : Do you face memory issues when creating your dataset using`SpeakerDiarizationDataset` or during  preprocessing with the `Preprocess` class (as in [here](https://github.com/huggingface/diarizers/blob/326acf21689ef231c29532e161030a97e4fd8b7b/train_segmentation.py#L113)) ? 

Hope it will help you!

**Comment by Jamiroquai88** [comment]
I created a PR here: https://github.com/huggingface/diarizers/pull/9/files
Please note that when using callhome in your training script it does not use `.construct_dataset()`
Feel free to use my script, should be pretty straightforward - just put all wavs and rttms into one directory.

**Comment by Jamiroquai88** [comment]
Hello @kamilakesbi, did you have a chance to look at my PR?

**Comment by kamilakesbi** [comment]
Hi @Jamiroquai88 not yet sorry! I'll try to have a look at it early next week :)

**Comment by Jamiroquai88** [comment]
Hi @kamilakesbi, let me know, if you need some help with this!

**Comment by v-nhandt21** [comment]
I have filtered all audios which are longer than 5 min, then increase the batch_size to 16, then it works smoothly 

```
train_set = dataset[str(train_split_name)].map(
            lambda file: preprocessor(file, random=False, overlap=0.5), 
            num_proc=1,#data_args.preprocessing_num_workers, 
            remove_columns=next(iter(dataset.values())).column_names,
            batched=True, 
            batch_size=16
        ).with_format("torch")
```

**Comment by Jamiroquai88** [comment]
so you used all that are LONGER than 5 mins?

**Comment by v-nhandt21** [comment]
> so you used all that are LONGER than 5 mins?

No, I use audios with a duration < 5 min only , I am not sure it is the main issue or not, but it works in my case, RTX3060 and 64GB Ram

**Comment by Jamiroquai88** [comment]
oh, that's not an option for me. All (99%+) my audios are longer than 5 mins.

**Comment by Jamiroquai88** [comment]
@kamilakesbi Please, let me know if you plan to work on this. Otherwise, feel free to close.
